from os import getenv

SECRET_KEY = getenv('SECRET_KEY')
SQLALCHEMY_DATABASE_URI = getenv('SQLALCHEMY_DATABASE_URI')

CLOUDINARY_CLOUD_NAME = getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = getenv('CLOUDINARY_API_SECRET')
