"""POGGERS1

Revision ID: 147291777b74
Revises: 
Create Date: 2022-10-31 07:23:51.169456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '147291777b74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_ibfk_1', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'colleges', ['resp_college'], ['college_code'], ondelete='SET DEFAULT')
    op.alter_column('student', 'course',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'courses', ['course'], ['course_code'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'courses', ['course'], ['course_code'])
    op.alter_column('student', 'course',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_ibfk_1', 'courses', 'colleges', ['resp_college'], ['college_code'])
    # ### end Alembic commands ###
