"""POGGERS2

Revision ID: 4365b8cfa924
Revises: 147291777b74
Create Date: 2022-10-31 07:25:06.141157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4365b8cfa924'
down_revision = '147291777b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_ibfk_1', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'colleges', ['resp_college'], ['college_code'], ondelete='SET DEFAULT')
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'courses', ['course'], ['course_code'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'courses', ['course'], ['course_code'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_ibfk_1', 'courses', 'colleges', ['resp_college'], ['college_code'])
    # ### end Alembic commands ###
