"""returned

Revision ID: 4599633c9102
Revises: 585b6803f3bd
Create Date: 2022-10-31 20:44:25.317118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4599633c9102'
down_revision = '585b6803f3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_ibfk_1', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'colleges', ['resp_college'], ['college_code'], ondelete='SET DEFAULT')
    op.drop_constraint('student_ibfk_2', 'student', type_='foreignkey')
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'courses', ['course'], ['course_code'], ondelete='SET DEFAULT')
    op.drop_column('student', 'college')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('college', mysql.VARCHAR(length=150), nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'colleges', ['college'], ['college_code'])
    op.create_foreign_key('student_ibfk_2', 'student', 'courses', ['course'], ['course_code'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_ibfk_1', 'courses', 'colleges', ['resp_college'], ['college_code'])
    # ### end Alembic commands ###
