"""added college in student

Revision ID: ac3295914a62
Revises: 4365b8cfa924
Create Date: 2022-10-31 20:30:11.636703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3295914a62'
down_revision = '4365b8cfa924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_ibfk_1', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'colleges', ['resp_college'], ['college_code'], ondelete='SET DEFAULT')
    op.add_column('student', sa.Column('college', sa.String(length=150), nullable=True))
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'courses', ['course'], ['course_code'], ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'student', 'colleges', ['college'], ['college_code'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'courses', ['course'], ['course_code'])
    op.drop_column('student', 'college')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_ibfk_1', 'courses', 'colleges', ['resp_college'], ['college_code'])
    # ### end Alembic commands ###
